development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sG_Media_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sG_Media_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sG_Media_production
  pool: 5
  username: root
  password:
  host: localhost
